### ISSUE TITLE
Got 2 Fortegreen colors in one lobby! + a suggestion

### ISSUE THREAD

**Issue by Dipek** [Koupah/Among-Us-Editor#12]
As it said the README, if you make the value more than 12 you can actually have more than one Fortegreen color! Here is photographic evidence.
https://imgur.com/a/ylCrI7l
I suggest to add more fortegreens. So if you select fortegreen in the editor it will ask which number to use.

**Comment by Koupah** [comment]
You can already do this by having them all as 12. Their color ID isn't a valid color, causing an error to happen making them Fortegreen. 12 isn't the code for Fortegreen, there is no color code for Fortegreen. Everything outside the 12 colors (0-11) causes an exception thus not changing your color from the default that is Fortegreen.

To summarise, this doesn't need to be added because it already works. Multiple people can use color ID 12 and join the same game. I've tested multiple times with friends and just then with myself.
![image](https://user-images.githubusercontent.com/25888315/95643305-c432ed00-0af1-11eb-95a9-05739db8aa19.png)
