### ISSUE TITLE
Among us havks

### ISSUE THREAD

**Issue by Sampson2304** [Koupah/Among-Us-Editor#16]

**Comment by Vresod** [comment]
Are you asking for hacks? Because that's not what this project is.
![Source from project owner](https://user-images.githubusercontent.com/40863375/97518055-d96e9f00-196c-11eb-9a14-c02d7a6f54ef.png)

**Comment by Koupah** [comment]
I've made it very clear many times I will not be adding cheats, as the screenshot that Vresod posted shows, many people have asked and continue to ask and I will always deny. 
This game is one I don't want to see ruined with cheaters, it's meant to be a fun game about lying & deceit but going that extra step and cheating is horrible.

Some people will claim this editor is a cheat, but it isn't. They believe this because of the new ability to change the host options but I disagree because the host options affect **everyone**. Players can see a lobby's settings and leave if they don't like them too. 

So no, to answer the question I assume you're asking, this is not a cheat and never will be.
