### ISSUE TITLE
How to change gameHostOptions?

### ISSUE THREAD

**Issue by Byllfighter** [Koupah/Among-Us-Editor#32]
How to change Max Players, Map and Impostors?

**Comment by Koupah** [comment]
Those numbers aren't changeable within the editor, if you'd like to add it yourself you can and you can even create a PR and I'd probably add it (with warnings).

The main reason they aren't in the editor is due to the fact the game force sets them back when out of their limits and you can just set them in game to numbers within the limits (thus making it useless).
