### ISSUE TITLE
Windows doesn't let me run the .exe

### ISSUE THREAD

**Issue by shloakvatsyayan** [Koupah/Among-Us-Editor#40]
Windows SmartScreen doesn't let me run the .exe file saying 'Windows Protected Your PC" but I know it's safe. The .jar file works but could you fix the .exe if it is something you can and not my computer? This is only with the newest version. Also it didn't let me run it because it was an unrecognized app.

**Comment by Koupah** [comment]
In windows settings you can change the SmartScreen settings to allow you to run the application.
I believe this issue is happening with the .exe file as I am self signing it, I'm not really knowledgable in that field though.

If you can't change your SmartScreen settings, just stick to the Java version as I can't really do much about it. Sorry.
