### ISSUE TITLE
Not working in private games

### ISSUE THREAD

**Issue by AdamKHacklaender** [Koupah/Among-Us-Editor#8]
I was told by my friends that this doesn't work in private games, and that my outfit is seen only in the intro screen. Is this true or is there something I am doing wrong? Thanks!

**Comment by mlucap** [comment]
Are you using this before launching the game? That is the only way it will work.

**Comment by AdamKHacklaender** [comment]
> Are you using this before launching the game? That is the only way it will work.

Yes! And it certainly shows in public games I join, as people comment 'nice outfit' in the lobby, but never when I join private games. Might ask more people next time to test it.

**Comment by Koupah** [comment]
Sometimes, the game doesn't show cosmetics to people who joined after you.

So if you join then your friends join, there's a chance they won't see your outfit. It might also happen the other way around too where you join your friends and you can't see their costume and you may not even realise. 

It's very frustrating but I can assure you, this is the games fault 100%. The way the editor sets your costume wouldn't differ from public or private games, it's simply just because in some situations the game refuses to tell other players what you're wearing.
